# This file was generated by GoReleaser. DO NOT EDIT.
cask "astra-video" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "acb231b9459d204705ac94d04aef08e9bcc7e3066a74cbda650ffa546da7f6b6"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9b95d9c4f80996fc80c1f5be3ecc3ae92feda4d968dc4ee271aeebaecc8af148"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24e1c860766d9d18412b23125e9ecf2e9fcef23a67ab1f95e2ec1dad533c76a3"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "332533506b38fa7c30391fc526075911a84aa255f4d69f9a45e8ebe36ebfc7cd"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "astra-video"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astra-video"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/astra-video"],
                   sudo: false
  end

  # No zap stanza required

  caveats <<~EOS
    Run `astra-video --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
