# This file was generated by GoReleaser. DO NOT EDIT.
cask "astra-video" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2a1eb36381a0600b278982cf06dbebfbf1239102b8eddb8f823230845e585dc5"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fb5bd425d008dd2cd7291d490526807afcf9eca7132fe002a62d5378434d4d1d"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62441992f5a495455b5d625c39ce790435073a8f70fcd8a8812cb8faaabc937e"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a6e82768d5e9b1192099b9b364280efbe46c66f3d6f05b4bd71a2981919ac085"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "astra-video"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astra-video"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/astra-video"],
                   sudo: false
  end

  # No zap stanza required

  caveats <<~EOS
    Run `astra-video --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
