# This file was generated by GoReleaser. DO NOT EDIT.
cask "astra-video" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d9e55c404708c825c45727f0753152f0f9f0f6d1e9fdeb648794fab3656731a6"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6a9b6323707b28ae9666da73933c238037de3db8e5fc77a54be50364530f046c"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24e1c860766d9d18412b23125e9ecf2e9fcef23a67ab1f95e2ec1dad533c76a3"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "332533506b38fa7c30391fc526075911a84aa255f4d69f9a45e8ebe36ebfc7cd"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/astra-video_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "astra-video"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astra-video"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/astra-video"],
                   sudo: false
  end

  # No zap stanza required

  caveats <<~EOS
    Run `astra-video --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
