# This file was generated by GoReleaser. DO NOT EDIT.
cask "uavideo-factory" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0c8abaed80746d9e12dfc55563e01eac149268888038211c459e2b495687f563"
      url "https://github.com/thientranhung/UAVideo-Variant-Factory/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ef5c40332679dc77944005fc13a17b9f1c960eefdd3d1095e43921eddef6934"
      url "https://github.com/thientranhung/UAVideo-Variant-Factory/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2a3d21e0dfef725f26c720dc9ebf2323c59c1ac997129e1dfe2cc661b33f730"
      url "https://github.com/thientranhung/UAVideo-Variant-Factory/releases/download/v#{version}/uavideo-factory_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5e1d54d49812cf1d142d50ea93ed779c8cce0b2dd0f297c9c7187d5107249296"
      url "https://github.com/thientranhung/UAVideo-Variant-Factory/releases/download/v#{version}/uavideo-factory_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "uavideo-factory"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uavideo-factory"

  # No zap stanza required

  caveats <<~EOS
    Run `uavideo-factory --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
