# This file was generated by GoReleaser. DO NOT EDIT.
cask "uavideo-factory" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e6e3c53127fabd930b9c14d40f030662bb1c9ae619f61991434f6c3325382218"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5ce4aadf032161967467c858e42afee22c4b01566daa1bfbf6db3a87baf6b699"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd5757b5edde7b058b69fbd463768d2b47dbffae2340faf49f062345e659fdab"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "02e382f080a9421eb03d0ee04c6a41843e15a1c9b2adc14180e5cc21aa88b693"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "uavideo-factory"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uavideo-factory"

  # No zap stanza required

  caveats <<~EOS
    Run `uavideo-factory --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
