# This file is generated by the UAVideo release process.
cask "uavideo-factory" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "948e1fc7a35e069915f0f5d3f1c7474e9e99eed823a74bf0e2a050e9c8d1b79f"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c6d3a87d8a1100a8a9d2d7e0230bcefee12226d1adf8f99bb12ddd6c6049f9fe"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "969cc1ce5db8bd4e3fc1a2d8dddc22f4264a133829b82912b54e411ef7907632"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "19af100757ec25e931a9517cfd7e4d8264f767f9963ef9ebec782edd3157d8fb"
      url "https://github.com/thientranhung/homebrew-tap/releases/download/v#{version}/uavideo-factory_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "uavideo-factory"
  desc "CLI for producing storyboard-based social video variants"
  homepage "https://github.com/thientranhung/UAVideo-Variant-Factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uavideo-factory"

  # No zap stanza required

  caveats <<~EOS
    Run `uavideo-factory --help` to inspect the production workflow.
    Rendering requires ffmpeg, ffprobe, Node.js, npm, npx, and HyperFrames.
  EOS
end
